# Generated by Django 3.1.7 on 2021-05-21 09:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Phone number')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('gender', models.CharField(max_length=255, verbose_name='Gender')),
                ('is_realtor', models.BooleanField(default=True, verbose_name='Realtor')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Promote to manager')),
                ('is_head_manager', models.BooleanField(default=False, verbose_name='Promote to head manager')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=main.utilities.get_path, verbose_name='Image')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Coefficient name')),
                ('coefficient', models.FloatField(verbose_name='Coefficient')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lead name')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone number')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('start_price', models.BigIntegerField(blank=True, null=True, verbose_name='Start price')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Added day')),
                ('percent', models.FloatField(default=0.15, verbose_name='Income percent')),
                ('company_percent', models.FloatField(default=0.1, verbose_name='Company percent')),
                ('deal_value', models.IntegerField(default=0, verbose_name='Deal cost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=main.utilities.get_path, verbose_name='Image')),
                ('date_closed', models.DateField(blank=True, null=True, verbose_name='Date closed')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Option name')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Status name')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locality')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('main_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main street')),
                ('secondary_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary street')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='House number')),
                ('apartment_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apartment number')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.option', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Current realtor'),
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Consumption name')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Lead')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_path, verbose_name='Image')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Additional image',
                'verbose_name_plural': 'Additional images',
            },
        ),
    ]
