# Generated by Django 3.1.7 on 2021-05-22 03:00

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utilities.get_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Consumption name'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Lead'),
        ),
    ]
